### ISSUE TITLE
Quote from Bill Gates

### ISSUE THREAD

**Issue by yazHak** [alma999/Physics#8]
![image](https://user-images.githubusercontent.com/52636425/63984007-49e30d00-ca97-11e9-845b-02831e91d94b.png)

**Comment by AbdullahIbin** [comment]
hello from Earth!

**Comment by mary1970** [comment]
Hi, everyone!

**Comment by nurBetul** [comment]
I would never choose a lazy guy because I can not take the risk. That guy maybe will not do the job instead of trying to do it in an easy way. I would prefer a hardworking guy.

**Comment by mude1053** [comment]
I WILL CHOOSE LAZ GUYS COZ THEY THINK OTHER WAY
